[project]
name = "space-race"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
[project.scripts]
space_race = "space_race.__main__:main"
